### ISSUE TITLE
Almost all of the settings have stopped working

### ISSUE THREAD

**Issue by kitsun-ho** [unlayer/vue-email-editor#106]
![截圖 2024-10-01 10 23 16](https://github.com/user-attachments/assets/584ac37e-5687-498c-bf5a-0df8ff6cfb17)
![截圖 2024-10-01 10 24 21](https://github.com/user-attachments/assets/757e7e34-4d0b-4f7e-8b00-b44eaee059d0)
![截圖 2024-10-01 10 25 09](https://github.com/user-attachments/assets/4618e33d-e40c-4039-b0c1-647e8da0deef)
![截圖 2024-10-01 10 28 20](https://github.com/user-attachments/assets/18e05ca0-8d7d-42b4-9af5-b77838df575f)

**Comment by omerzahidbajwa** [comment]
Hi, are you passing in a projectId? if not please do so.

**Comment by SYJ0905** [comment]
After adding the project ID, I started http://localhost:8080/ on my local machine and added http://localhost:8080/ to the Allowed Domain(s). However, my language is still not working.
![Uploading 截圖 2024-10-03 清晨6.04.21.png…]()

**Comment by omerzahidbajwa** [comment]
Hi, Unlayer has launched new pricing plans and the new "Free" plan is very limited so theres a few things that have to be ensured:
- The projectId your using is on "Free (Legacy)" plan, you can confirm that by going to the "billing" section of your workspace within console.unlayer.com (you will only have this plan available for old projectIds and workspaces)
- All new workspaces and projects will come with the limited Free plan.
- Adding localhost is not required, you only have to add the live domain to the "Allowed Domains" list.
- You should be able to test if you have access to specific feature sets on local host by simply adding the projectId

For the case above that specific projectId seems to be on the new "Free" plan

**Comment by MikeCraig418** [comment]
> Hi, Unlayer has launched new pricing plans and the new "Free" plan is very limited so theres a few things that have to be ensured:
> 
> * The projectId your using is on "Free (Legacy)" plan, you can confirm that by going to the "billing" section of your workspace within console.unlayer.com (you will only have this plan available for old projectIds and workspaces)
> * All new workspaces and projects will come with the limited Free plan.
> * Adding localhost is not required, you only have to add the live domain to the "Allowed Domains" list.
> * You should be able to test if you have access to specific feature sets on local host by simply adding the projectId
> 
> For the case above that specific projectId seems to be on the new "Free" plan

Well, thank you for the generous features previously allotted in the FREE plan. 

However, now that I can't paste in simple formatting from rich text, I can tell you your widget is nearly unusable. It's a shame... I had previously recommended this platform to so many people. But I can no longer do that and will be looking for a replacement.

In fact, Unlayer reminds me of [GrapesJS](https://grapesjs.com/). However, even though GrapesJS now has a paid Studio offering, their pricing is much more amenable:

![image](https://github.com/user-attachments/assets/f945567d-4358-4888-8c06-77a051f99d64)

**Comment by adeelraza** [comment]
@MikeCraig418 thank you for your feedback. However, pasting should be working as expected.
