### ISSUE TITLE
Merge tag support?

### ISSUE THREAD

**Issue by ColinRosati** [unlayer/vue-email-editor#2]
Is there support for the merge tags?

I have noticed there is no setMergeTags method in the Vue, or Angular repos only react.

I have tried to grab the setMergeTags from the react repo and put it into EmailEditor.vue but getting reference errors. I thought maybe this would work modifying my EmailEditor component. But I assume it may be further up in the  imported "//editor.unlayer.com/embed.js" file.

`setMergeTags(mergeTags){
      unlayer.setMergeTags(mergeTags)
    }` 

as well as initializing 

```
 unlayerScript.onload = () => {
      this.loadEditor();
      this.modifyStyle();
      this.setMergeTags();
    };

  if (this.mergeTags) {
        options.mergeTags = this.mergeTags
      }

unlayer.init({
        ...options,
        id: 'editor',
        displayMode: 'email',
        appearance: {
          theme: 'dark'
        },
        mergeTags: {}
      });
```

the reference Error is 

>  ReferenceError: unlayer is not defined
>     at c.setMergeTags (EmailEditor.vue:88)

**Comment by adeelraza** [comment]
@ColinRosati1 You can pass it in properties as `options`.

**Comment by jameswagoner** [comment]
I needed to load my design and merge tags after editor is initialized. You can accomplish using `setMergeTags()` by accessing the `editor` instance.

```js
const editor = ref();

function loadData() {
  editor.value.loadDesign({});

  editor.value.editor.setMergeTags({});
}

<EmailEditor ref="editor" ... @load="loadData" />
```
