### ISSUE TITLE
Editor seen in the screen is too small.

### ISSUE THREAD

**Issue by jayanthbagare** [unlayer/vue-email-editor#21]
Hi 
The editor in seen in the build screen is too small. Attached is a screenshot.

![Screen Shot 2020-12-11 at 5 57 19 PM](https://user-images.githubusercontent.com/290588/101903455-529f1a00-3bda-11eb-8f3f-e1ff0f5adf64.png)

**Comment by mahfuzdiu** [comment]
try this <EmailEditor ref="emailEditor" v-on:load="editorLoaded" style="height: 700px; "/>

**Comment by mahfuzdiu** [comment]
<EmailEditor ref="emailEditor" v-on:load="editorLoaded" style="height: 700px; "/>

**Comment by mahfuzdiu** [comment]
add style after v-on:load="editorLoaded" style="height: 700px; "

**Comment by jayanthbagare** [comment]
Thanks is there a way to do this via the parameters.
