### ISSUE TITLE
I can't add image in the editor. It return CORS error 

### ISSUE THREAD

**Issue by Tesfamariam12** [unlayer/vue-email-editor#77]

**Comment by Tesfamariam12** [comment]
This Code solved the issue!
....
this.$refs.emailEditor.editor.registerCallback('image', function(file, done) {
  var data = new FormData()
  data.append('file', file.attachments[0])

  fetch('/uploads', {
    method: 'POST',
    headers: {
      'Accept': 'application/json'
    },
    body: data
  }).then(response => {
    // Make sure the response was valid
    if (response.status >= 200 && response.status < 300) {
      return response
    } else {
      var error = new Error(response.statusText)
      error.response = response
      throw error
    }
  }).then(response => {
    return response.json()
  }).then(data => {
    // Pass the URL back to Unlayer to mark this upload as completed
    done({ progress: 100, url: data.filelink })
  })
})
....

**Comment by Vitomir2** [comment]
> 

Hi @tesfamariam1,

Can you share what you have done on the back-end for the /uploads endpoint?
